ALTER TABLE clients ADD COLUMN IF NOT EXISTS dob DATE;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS age INTEGER;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS sex TEXT CHECK (sex IN ('Homme', 'Femme', 'Autre'));
ALTER TABLE clients ADD COLUMN IF NOT EXISTS height NUMERIC;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS weight NUMERIC;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS energy_expenditure_level TEXT CHECK (energy_expenditure_level IN ('sedentary', 'lightly_active', 'moderately_active', 'very_active', 'extremely_active'));
ALTER TABLE clients ADD COLUMN IF NOT EXISTS objective TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active' CHECK (status IN ('active', 'prospect', 'inactive'));
ALTER TABLE clients ADD COLUMN IF NOT EXISTS lifestyle JSONB DEFAULT '{}'::jsonb;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS medical_info JSONB DEFAULT '{}'::jsonb;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS nutrition JSONB DEFAULT '{}'::jsonb;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS bilans JSONB DEFAULT '[]'::jsonb;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS assigned_bilans JSONB DEFAULT '[]'::jsonb;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS nutrition_logs JSONB DEFAULT '[]'::jsonb;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS performance_logs JSONB DEFAULT '[]'::jsonb;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS assigned_nutrition_plans JSONB DEFAULT '[]'::jsonb;
CREATE INDEX IF NOT EXISTS idx_clients_bilans ON clients USING GIN (bilans);
CREATE INDEX IF NOT EXISTS idx_clients_medical_info ON clients USING GIN (medical_info);
CREATE INDEX IF NOT EXISTS idx_clients_nutrition ON clients USING GIN (nutrition);
CREATE INDEX IF NOT EXISTS idx_clients_status ON clients (status);
CREATE INDEX IF NOT EXISTS idx_clients_coach_id ON clients (coach_id);
SELECT 'Migration terminée avec succès!' AS message;
